language: java

sudo: false

install: true

dist: trusty

jdk:
- oraclejdk8

os:
- linux

branches:
  only:
  - develop

before_cashe:
- rm -f $HOME/.gradle/cashes/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/cashes/*/plugin-resolution/

cashes:
  directories:
  - $HOME/.gradle/cashes/
  - $HOME/.gradle/wrapper/

addons:
sonarcloud:
organization: $SONARCLOUD_ORGANIZATION
  token:
  secure: $SONARCLOUD_TOKEN

script:
- ./gradlew assemble
- ./gradlew check --rerun-tasks
- sonar-scanner
- rm -rf .scannerwork